-- This file was initialised from `FunsExternal_Template.lean` (generated by Aeneas).
-- [ethlambda_verification]: external functions.
-- These are real computable Lean implementations of the five Rust shims that
-- Aeneas leaves abstract. With these in place the entire generated pipeline
-- (state_transition, process_block, process_attestations, ...) becomes
-- computable, even though Funs.lean is wrapped in `noncomputable section`:
-- Lean only suppresses IR for definitions whose bodies actually reference
-- something it cannot compile, so providing real defs here is sufficient.
-- `FunsExternal_Template.lean` is refreshed on every Aeneas run and remains
-- the canonical signature reference — diff it against this file to catch
-- upstream signature drift.
import Aeneas
import ConsensusLean4.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open ethlambda_verification

/-- [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering> for core::cmp::Ordering}::eq] -/
@[rust_fun
  "core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq"]
def core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq
    : Ordering → Ordering → Result Bool
  | .lt, .lt => ok true
  | .eq, .eq => ok true
  | .gt, .gt => ok true
  | _,   _   => ok false

/-- [core::result::{core::ops::try_trait::Try< ... > for core::result::Result<T,E>}::branch] -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
def core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
    {T : Type} {E : Type} :
    core.result.Result T E →
    Result (core.ops.control_flow.ControlFlow
      (core.result.Result core.convert.Infallible E) T)
  | core.result.Result.Ok  t => ok (core.ops.control_flow.ControlFlow.Continue t)
  | core.result.Result.Err e =>
      ok (core.ops.control_flow.ControlFlow.Break (core.result.Result.Err e))

/-- [core::result::{core::ops::try_trait::FromResidual< ... > for core::result::Result<T,F>}::from_residual] -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
def core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
    (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
    core.result.Result core.convert.Infallible E →
    Result (core.result.Result T F)
  | core.result.Result.Ok  inf => nomatch inf
  | core.result.Result.Err e   => do
      let f ← convertFromInst.from_ e
      ok (core.result.Result.Err f)

/-- [alloc::vec::{alloc::vec::Vec<T>}::clear] — discard all elements. -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::clear"]
def alloc.vec.Vec.clear
    {T : Type} (_A : Type) (_v : alloc.vec.Vec T) : Result (alloc.vec.Vec T) :=
  ok (alloc.vec.Vec.new T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty] -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
def alloc.vec.Vec.is_empty
    {T : Type} (_A : Type) (v : alloc.vec.Vec T) : Result Bool :=
  ok (decide (v.length = 0))
