-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ethlambda_verification]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import ConsensusLean4.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open ethlambda_verification

/-- [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering> for core::cmp::Ordering}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 389:43-389:52
    Name pattern: [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq]
    Visibility: public -/
@[rust_fun
  "core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq"]
axiom core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq
  : Ordering → Ordering → Result Bool

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [alloc::vec::{alloc::vec::Vec<T>}::clear]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2903:4-2903:27
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::clear]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::clear"]
axiom alloc.vec.Vec.clear
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (alloc.vec.Vec T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2956:4-2956:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

