-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ethlambda_verification]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace ethlambda_verification

/-- [ethlambda_verification::types::H256]
    Source: 'crates/verification/src/types.rs', lines 3:0-3:30
    Visibility: public -/
@[reducible]
def types.H256 := Array Std.U8 32#usize

/-- [ethlambda_verification::types::Checkpoint]
    Source: 'crates/verification/src/types.rs', lines 59:0-62:1
    Visibility: public -/
structure types.Checkpoint where
  root : types.H256
  slot : Std.U64

/-- [ethlambda_verification::types::AttestationData]
    Source: 'crates/verification/src/types.rs', lines 75:0-80:1
    Visibility: public -/
structure types.AttestationData where
  slot : Std.U64
  head : types.Checkpoint
  target : types.Checkpoint
  source : types.Checkpoint

/-- [ethlambda_verification::state_transition::Error]
    Source: 'crates/verification/src/state_transition.rs', lines 8:0-18:1
    Visibility: public -/
@[discriminant isize]
inductive state_transition.Error where
| StateSlotIsNewer : state_transition.Error
| SlotMismatch : state_transition.Error
| ParentSlotIsNewer : state_transition.Error
| InvalidProposer : state_transition.Error
| InvalidParent : state_transition.Error
| NoValidators : state_transition.Error
| StateRootMismatch : state_transition.Error
| SlotGapTooLarge : state_transition.Error
| ZeroHashInJustificationRoots : state_transition.Error

/-- [ethlambda_verification::types::Validator]
    Source: 'crates/verification/src/types.rs', lines 123:0-126:1
    Visibility: public -/
structure types.Validator where
  pubkey : Array Std.U8 52#usize
  index : Std.U64

/-- [ethlambda_verification::types::ChainConfig]
    Source: 'crates/verification/src/types.rs', lines 117:0-119:1
    Visibility: public -/
structure types.ChainConfig where
  genesis_time : Std.U64

/-- [ethlambda_verification::types::BlockHeader]
    Source: 'crates/verification/src/types.rs', lines 91:0-97:1
    Visibility: public -/
structure types.BlockHeader where
  slot : Std.U64
  proposer_index : Std.U64
  parent_root : types.H256
  state_root : types.H256
  body_root : types.H256

/-- [ethlambda_verification::types::State]
    Source: 'crates/verification/src/types.rs', lines 135:0-146:1
    Visibility: public -/
structure types.State where
  config : types.ChainConfig
  slot : Std.U64
  latest_block_header : types.BlockHeader
  latest_justified : types.Checkpoint
  latest_finalized : types.Checkpoint
  historical_block_hashes : alloc.vec.Vec types.H256
  justified_slots : alloc.vec.Vec Bool
  validators : alloc.vec.Vec types.Validator
  justifications_roots : alloc.vec.Vec types.H256
  justifications_validators : alloc.vec.Vec Bool

/-- [ethlambda_verification::types::AggregatedAttestation]
    Source: 'crates/verification/src/types.rs', lines 84:0-87:1
    Visibility: public -/
structure types.AggregatedAttestation where
  aggregation_bits : alloc.vec.Vec Bool
  data : types.AttestationData

/-- [ethlambda_verification::types::BlockBody]
    Source: 'crates/verification/src/types.rs', lines 101:0-103:1
    Visibility: public -/
structure types.BlockBody where
  attestations : alloc.vec.Vec types.AggregatedAttestation

/-- [ethlambda_verification::types::Block]
    Source: 'crates/verification/src/types.rs', lines 107:0-113:1
    Visibility: public -/
structure types.Block where
  slot : Std.U64
  proposer_index : Std.U64
  parent_root : types.H256
  state_root : types.H256
  body : types.BlockBody

end ethlambda_verification
